campus:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: campus_delivery
    username: root
    password: 123456

  alioss:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      accessKeyId: LTAI5tQqNCBH7qmGTJehiuTR
      accessKeySecret: dqkUe6X8KfMuqM2F10RvrUzC6dd4rx
      bucketName: campus-delivery-unique

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx734c04362042bdec
    secret: 13dcd05e02583e8126991ffdf4955f98
